
/vis/disable
/tracking/storeTrajectory 0
/gps/particle ion



#--------------------------------------------------------------
# Co60
/shielding/thickness 1.0
/gps/ion 27 60
/run/beamOn 10000


#--------------------------------------------------------------
# Co60
/shielding/thickness 26.0
/gps/ion 27 60
/run/beamOn 10000


#--------------------------------------------------------------
# Co60
/shielding/thickness 50.0
/gps/ion 27 60
/run/beamOn 10000


#--------------------------------------------------------------
# Cs137
/shielding/thickness 1.0
/gps/ion 55 137
/run/beamOn 10000


#--------------------------------------------------------------
# Cs137
/shielding/thickness 26.0
/gps/ion 55 137
/run/beamOn 10000


#--------------------------------------------------------------
# Cs137
/shielding/thickness 50.0
/gps/ion 55 137
/run/beamOn 10000


#--------------------------------------------------------------
# Eu152
/shielding/thickness 1.0
/gps/ion 63 152
/run/beamOn 10000


#--------------------------------------------------------------
# Eu152
/shielding/thickness 26.0
/gps/ion 63 152
/run/beamOn 10000


#--------------------------------------------------------------
# Eu152
/shielding/thickness 50.0
/gps/ion 63 152
/run/beamOn 10000
